### ISSUE TITLE
Create repository for e-mobility widget by belka

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/mobility.meran.eu#25]

**Comment by bertolla** [comment]
@rcavaliere  Is there a specific name you want to use for the repository. My suggestion would be **e-mobility-webcomponent**

**Comment by bertolla** [comment]
@rcavaliere Ping!! :hourglass_flowing_sand:

**Comment by ohnewein** [comment]
Let's call it odh-web-components and have it as common repository for all web components.

**Comment by bertolla** [comment]
@ohnewein @rcavaliere 
I created it with a small doc on how to contribute and made it a **private** repo. https://github.com/idm-suedtirol/odh-web-components.

**Comment by ohnewein** [comment]
@bertolla please open the repo as open repo
@rcavaliere please ask belka to provide us the source code

**Comment by bertolla** [comment]
Done! I also informed them with Roberto in CC.

**Comment by rcavaliere** [comment]
Just sent another push, since I don't know if they have uploaded the source code yet...

**Comment by rcavaliere** [comment]
belka has informed me that they pushed the code. There are two web-apps: one for visualizing the charging stations, and one is a visualizer of statistics. See: 
https://clients.belka.us/noi/map.html
https://clients.belka.us/noi/dashboard.html
@bertolla, @ohnewein can deploy the web-apps and let them be accessible through new end-points?
Any ideas about their naming?

**Comment by ohnewein** [comment]
What about creating a subdomain structure on opendatahub.bz.it?
Let's say all components will be published under the subdomain: cmp.opendatahub.bz.it
Therefore for the specific web components the final subdomains would be:

- echarging-map.cmp.opendatahub.bz.it
- echarging-dashboard.cmp.opendatahub.bz.it

What do you think about this idea?

**Comment by rcavaliere** [comment]
@ohnewein for me it is fine.
By the way, what does "cmp" stand for?

**Comment by ohnewein** [comment]
@rcavaliere cmp stands for "component". I didn't want to use "wc" as short name ;-)

@Piiit suggests to not use too deep subdomains. His suggestion ist to use only one subdomain and folders for the single components. Something like:

- webcomponents.opendatahub.bz.it/echarging-map/
- webcomponents.opendatahub.bz.it/echarging-dashboard/

In the web component folder there will be the following content:

- index.html -> the preview page
- NAME_widget.min.js

**Comment by rcavaliere** [comment]
@ohnewein @Piiit for me this logic is ok as well.
Can you in the scope of the next sprint the domains activate and deploy the new web components so that they are reachable through these domains?
